name: 更新域名列表

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点（北京时间 8 点）
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'config/**'  # 配置文件变更时触发
      - 'scripts/**'  # 新增：脚本文件变更时触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必要权限：写入仓库

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史，避免 Git 问题

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: 创建必要文件
        run: |
          mkdir -p config dist
          # 国内 DNS（默认）
          if [ ! -f config/cn_dns.txt ]; then
            echo "https://doh.pub/dns-query" > config/cn_dns.txt
            echo "https://dns.alidns.com/dns-query" >> config/cn_dns.txt
          fi
          # 国外 DNS（默认）
          if [ ! -f config/foreign_dns.txt ]; then
            echo "https://1.1.1.1/dns-query" > config/foreign_dns.txt
            echo "https://8.8.8.8/dns-query" >> config/foreign_dns.txt
          fi
          # 自定义域名文件
          touch config/{custom_cn_domains,custom_foreign_domains}.txt

      - name: 生成配置文件
        run: |
          python scripts/generate_config.py || echo "配置生成失败，跳过后续"

      - name: 转换为 QuanX 格式
        run: |
          if [ -f scripts/domain_to_quanx.py ]; then
            python scripts/domain_to_quanx.py
          else
            echo "QuanX 脚本不存在，跳过转换"
          fi

      - name: 提交更新（优化版）
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .  # 添加所有变更文件
          # 检查变更（含未跟踪文件）
          if [ -z "$(git status --porcelain)" ]; then
            echo "无变更，跳过提交"
          else
            git commit -m "自动更新域名列表 $(date +'%Y-%m-%d %H:%M')"
          fi

      - name: 推送更新（社区稳定方案）
        uses: peaceiris/actions-github-push@v3  # 稳定动作，替代原方案
        if: github.ref_type == 'branch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "自动更新域名列表 $(date +'%Y-%m-%d')"
          branch: ${{ github.ref_name }}
          force: false
